### ISSUE TITLE
SBOL Industrial Summer Project Ideas Template

### ISSUE THREAD

**Issue by hasanbaig** [SynBioDex/SBOL-Industrial-Summer-Program#1]
# SBOL Industrial Summer Project Ideas Template
### Background
Describe the current state of the project and the main problem or issue being addressed by the proposed idea. Details should include links and references. 

### Goal
Describe what the end result of the SISP project should be.

### Difficulty Level X
Give a difficulty level (to replace X) from 1-3, with 1 easiest and 3 hardest. Make sure to tag the issue with this difficulty.
Describe with a sentence or two why the project is this difficulty level.

### Skills
List skills/technologies that the student should be familiar with. Also tag the issue with these.

Essential skills: Java, Cytoscape
Nice to have skills: GPU programming 

### Public Repository
Please link to a public, open-source repository for your project. _All code from accepted projects must be open source and public throughout the project period and beyond._ 

### Potential Mentors
List the names and email contacts for potential mentors.

**Comment by cjmyers** [comment]
Hi,

This looks good to me.

Thanks,
Chris

**Comment by hasanbaig** [comment]
Template created under issue settings.
