### ISSUE TITLE
SynBioHub Excel integration

### ISSUE THREAD

**Issue by JMante1** [SynBioDex/SBOL-Industrial-Summer-Program#2]
### Background
Currently there is an initial version of a python library (https://github.com/SynBioDex/Excel-to-SBOL)  and python plugins (https://github.com/SynBioHub/Plugin-Submit-Excel-Library and https://github.com/SynBioHub/Plugin-Submit-Excel-Composition) to use excel spreadsheets to upload basic and composite components to SynBioHub.

### Goal
There are a lot of further extensions to the library and plugins to allow download, allow sbol 3 support, allow upload of non-component sbol, and allow other formats of data (e.g. Genbank reference ids, pubmed papers, and uniprot data). We would want to make progress towards these goals.

### Difficulty Level 2
Initial groundwork for the project has been put in place which makes it easier to build further. The scope of the project is broad so the student could work on an area to which they are the most suited. It has the potential to be a very expansive project which does also pose difficulties for the student.

### Skills
List skills/technologies that the student should be familiar with. Also tag the issue with these.
Essential: Python, Flask, Excel
Nice: SBOL, SynBioHub, GenBank, Uniprot

### Public Repository
A repo in:
https://github.com/SynBioDex or https://github.com/SynBioHub

### Potential Mentors
@cjmyers @JMante1

**Comment by jakebeal** [comment]
This was funded in the 2021 projects.
